#!/bin/bash
# Manual Docker start - paste these commands one by one in your terminal

echo "════════════════════════════════════════════════════════════════"
echo "COPY AND PASTE THESE COMMANDS ONE BY ONE:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. Add to docker group:"
echo "   sudo usermod -aG docker \$USER"
echo ""
echo "2. Activate group:"
echo "   newgrp docker"
echo ""
echo "3. Test docker:"
echo "   docker ps"
echo ""
echo "4. Start application:"
echo "   docker-compose up -d"
echo ""
echo "5. Check status:"
echo "   docker-compose ps"
echo ""
echo "6. Access application:"
echo "   http://localhost:3000"
echo ""
echo "════════════════════════════════════════════════════════════════"
