import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { MapPin, AlertTriangle, CheckCircle } from 'lucide-react';
import api from '../services/api';
import SensorHeatmap2D from '../components/SensorHeatmap2D';
import MethodCard from '../components/MethodCard';

const apiBase = import.meta.env.VITE_API_URL || (api?.defaults?.baseURL) || 'http://localhost:8000';

export default function DamageLocalization() {
  const { analysisId } = useParams();
  const [results, setResults] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchResults();
  }, [analysisId]);

  const fetchResults = async () => {
    try {
      const response = await api.get(`/api/v1/results/${analysisId}`);
      setResults(response.data);
      setLoading(false);
    } catch (error) {
      console.error('Error fetching results:', error);
      setLoading(false);
    }
  };

  if (loading) {
    return <div className="text-white">Loading...</div>;
  }

  return (
    <div className="max-w-7xl mx-auto">
      <h1 className="text-4xl font-bold text-white mb-8 flex items-center gap-3">
        <MapPin className="text-red-400" />
        Damage Localization
      </h1>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* 3D Visualization Area */}
        <div className="lg:col-span-2 bg-slate-800 rounded-lg p-8 border border-slate-700">
          <h2 className="text-2xl font-bold text-white mb-4">Damage Heatmap (2D)</h2>
          <SensorHeatmap2D sensorLayout={results?.sensor_layout} sensorScores={results?.sensor_damage_scores} />
          <div className="flex items-center justify-between mt-3">
            <p className="text-gray-400 text-sm">
              Coordinates are plotted in the same reference frame as the structure definition (origin at 0,0,0).
            </p>
            <div className="text-xs text-gray-400">Score: 0 → 1 (Blue → Red)</div>
          </div>
        </div>

        {/* Localization Details */}
        <div className="space-y-6">
          {/* Result Summary */}
          <div className="bg-slate-800 rounded-lg p-6 border border-slate-700">
            <h3 className="text-lg font-bold text-white mb-3">Result Summary</h3>
            <div className="text-sm text-gray-300 grid grid-cols-2 gap-3">
              <div>
                <div className="text-gray-400">Primary Sensor</div>
                <div className="text-white font-semibold">{results?.damage_primary_sensor ?? 'N/A'}</div>
              </div>
              <div>
                <div className="text-gray-400">Zone</div>
                <div className="text-white font-semibold">{results?.damage_zone ?? 'N/A'}</div>
              </div>
              <div>
                <div className="text-gray-400">Component</div>
                <div className="text-white font-semibold">{results?.damage_component ?? 'N/A'}</div>
              </div>
              <div>
                <div className="text-gray-400">Confidence</div>
                <div className="text-green-400 font-bold">{((results?.damage_confidence || 0) * 100).toFixed(0)}%</div>
              </div>
            </div>
          </div>
          {results?.reports?.localization_html && (
            <a
              href={`${apiBase}${results.reports.localization_html}`}
              target="_blank"
              rel="noreferrer"
              className="block bg-slate-800 rounded-lg p-4 border border-slate-700 hover:border-blue-500 transition"
            >
              <div className="text-white font-bold">Open Full HTML Localization Report</div>
              <div className="text-sm text-gray-400">Printable, judge-ready report generated by Phase‑2 VisualizationEngine</div>
            </a>
          )}
          <div className="bg-slate-800 rounded-lg p-6 border border-slate-700">
            <h3 className="text-lg font-bold text-white mb-3">Unified Verdict</h3>
            <div className="text-sm text-gray-300 space-y-1">
              <div>Scenario: <span className="text-white font-semibold">{results?.scenario_id}</span></div>
              <div>Damage type: <span className="text-white font-semibold">{results?.phase2_unified?.unified_diagnosis?.damage_type}</span></div>
              <div>Confidence: <span className="text-green-400 font-bold">{((results?.damage_confidence || 0) * 100).toFixed(0)}%</span></div>
              <div>Severity: <span className="text-white font-bold">{(results?.damage_severity || 0).toFixed(1)}%</span></div>
              <div>
                Q (Health Similarity): <span className="text-white font-bold">{((results?.q_index?.q || 0) * 100).toFixed(1)}%</span>
                <span className="text-xs text-gray-400"> (vs baseline)</span>
              </div>
            </div>
          </div>

          <div className="bg-slate-800 rounded-lg p-6 border border-slate-700">
            <h3 className="text-lg font-bold text-white mb-3">Per-Method Evidence</h3>
            <div className="grid grid-cols-1 gap-3">
              <MethodCard title="Spatial Mapping" result={results?.phase2_unified?.method_results?.spatial_mapping} />
              <MethodCard title="MAC Matrix" result={results?.phase2_unified?.method_results?.mac_matrix} />
              <MethodCard title="Wavelet Detector" result={results?.phase2_unified?.method_results?.wavelet} />
            </div>
          </div>
          {results?.damage_location && (
            <div className="bg-red-900 bg-opacity-30 border border-red-700 rounded-lg p-6">
              <div className="flex items-center gap-2 mb-4">
                <AlertTriangle className="text-red-400" />
                <h3 className="text-xl font-bold text-white">Damage Detected</h3>
              </div>
              <div className="space-y-3">
                <div>
                  <p className="text-gray-400 text-sm">Location from Origin (0,0,0)</p>
                  <p className="text-xl font-bold text-white">
                    ({results.damage_location.x?.toFixed(2)}, {results.damage_location.y?.toFixed(2)}, {results.damage_location.z?.toFixed(2)}) m
                  </p>
                  <p className="text-sm text-gray-300">Distance from origin: {results.damage_location.distance_from_origin?.toFixed(2)} m</p>
                </div>
                <div>
                  <p className="text-gray-400 text-sm">Component</p>
                  <p className="text-xl font-bold text-white">{results.damage_component || 'N/A'}</p>
                  <p className="text-sm text-gray-300">Sensor: {results.damage_primary_sensor || 'N/A'}</p>
                </div>
                <div>
                  <p className="text-gray-400 text-sm">Severity / Confidence</p>
                  <p className="text-xl font-bold text-white">{(results.damage_severity || 0).toFixed(1)}%</p>
                  <p className="text-2xl font-bold text-green-400">{(results.damage_confidence * 100).toFixed(0)}%</p>
                </div>
              </div>
            </div>
          )}

          <div className="bg-slate-800 rounded-lg p-6 border border-slate-700">
            <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
              <CheckCircle className="text-blue-400" />
              Recommendations
            </h3>
            <ul className="space-y-2 text-sm text-gray-300">
              {(results?.phase2_unified?.recommendation?.recommendations || []).length ? (
                results.phase2_unified.recommendation.recommendations.map((r, idx) => (
                  <li key={idx}>• {r}</li>
                ))
              ) : (
                <>
                  <li>• Review the damage zone on the heatmap</li>
                  <li>• Inspect the identified component and nearby connections</li>
                  <li>• Re-test after tightening/repair to confirm reduction in severity</li>
                </>
              )}
            </ul>
          </div>

          <div className="bg-blue-900 bg-opacity-30 border border-blue-700 rounded-lg p-6">
            <p className="text-blue-200 text-sm">
              Damage localization uses a hybrid approach combining physics-based modal analysis with machine learning for high-accuracy prediction.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
